### ISSUE TITLE
IMU合成数据

### ISSUE THREAD

**Issue by wdanc** [Xinyu-Yi/PIP#12]
很棒的工作，感谢作者！
想请问一下IMU数据的合成问题，在preprocess.py程序里的process_amass函数是做IMU数据合成的吧？里面用到的vi_mask和ji_mask是选取6个关节的位移和旋转矩阵，其中vi_mask对应网格顶点，ji_mask对应关节，这里取网格顶点位置算加速度的话，取的6个顶点[1961, 5424, 1176, 4662, 411, 3021]是有什么依据吗？是这几个顶点正好对应6个关节吗？如果是的话，请问您可以提供一下网格与关节对应关系的文件吗？

**Comment by Xinyu-Yi** [comment]
这六个顶点不对应关节，是我从mesh上近似挑了6个点，是imu大致的绑定位置

**Comment by Xinyu-Yi** [comment]
mesh顶点到关节位置的对应关系，你可以去参考smpl论文，里面有个j_regressor

**Comment by wdanc** [comment]
> mesh顶点到关节位置的对应关系，你可以去参考smpl论文，里面有个j_regressor

好的，非常感谢！
