### ISSUE TITLE
并行推断

### ISSUE THREAD

**Issue by yukichou** [Xinyu-Yi/PIP#13]
作者您好，代码的推断输入是一整个片段的，问个小白问题，实时单帧多人的并行推断的实现思路是怎样呢？

**Comment by Xinyu-Yi** [comment]
rnn可以用一个batch处理。物理模块好像只能一人一人运行。可以多线程试一下

**Comment by yukichou** [comment]
感谢作者回复！ 物理模块不支持batch操作，即使多线程也非常慢，占用大量的cpu资源，请问有什么方法能优化物理模块的并行处理能力？：）

**Comment by Xinyu-Yi** [comment]
这个我不清楚。你得去找找有没有能并行求解一堆问题的QP solver
