### ISSUE TITLE
Training and evaluation

### ISSUE THREAD

**Issue by yohanshin** [Xinyu-Yi/PIP#15]
Hi Xinyu,

I am trying to build an additional network upon your system and would like to ask you how did you train your model. Could you tell me approximately how many epochs you trained on synthetic data first and then fine-tuned on DIP-IMU?

Also when evaluating your model on TotalCapture dataset, did you test on all sequences in TotalCapture dataset, or did you only use a part of TotalCapture sequences?

Thank you so much in advance!

**Comment by Xinyu-Yi** [comment]
1) I train the network to converge, about 1 day for all networks, on 1080Ti.
2) all sequences as in my evaluation codes, except for one that have no ground-truth
