### ISSUE TITLE
如何训练模型

### ISSUE THREAD

**Issue by zxxtxwd** [Xinyu-Yi/PIP#16]
谢谢作者的优秀工作。请问您是怎么训练论文中的网络呢？是将每个运动序列作为一个batch输入到网络中，然后设置batch_size为1吗？我试验了一下将原始数据集分成固定时间长度的窗口后输入网络，设置batch_size为1024，在3090上进行训练，预训练阶段一个epoch要2个小时，训练的时间成本太高了。查看您的代码猜测是将整个运动序列输入到网络中进行训练，这样可以节省很多时间。您可以透漏一下训练的细节吗？比如训练方式、时间、以及论文中各个loss所占的权重？

**Comment by Xinyu-Yi** [comment]
一个epoch只要1-2分钟。论文里有写细节
