### ISSUE TITLE
Is the current evaluation offline?

### ISSUE THREAD

**Issue by dx118** [Xinyu-Yi/PIP#22]
Hi Xinyu,
 I wonder if the current evaluation code runs totally offline? and will the rnn hidden state be reused when running online evaluation?

**Comment by Xinyu-Yi** [comment]
Hi,

Yes, I find that it's the offline version. Maybe later today or tomorrow I'll update the live demo codes. You can check that.

**Comment by dx118** [comment]
ah, thank you

**Comment by Xinyu-Yi** [comment]
Hi, please check the livedemo branch

**Comment by 1009562910** [comment]
Run Live Demo with Noitom IMUs (recommended)
Why recommend Noitiom IMUs, but not Xense Bot. Is there any performance difference?
Xsens Bot is BLE protocal, How about Noitiom IMUs?

**Comment by Xinyu-Yi** [comment]
> Run Live Demo with Noitom IMUs (recommended) Why recommend Noitiom IMUs, but not Xense Bot. Is there any performance difference? Xsens Bot is BLE protocal, How about Noitiom IMUs?

In my experiments, I find that Noitom IMUs better leverage the magnetic measurement and thus do not suffer from pose drift (See the video where we sit on a chair for half an hour and the system can perform well using Noitom sensors). But Xsens drifts largely in orientation measurements and need frequent heading reset. This is just my own experiences. You can try the different sensors.

**Comment by 1009562910** [comment]
Will PIP live demo influenced by the magnetic environment? If yes, how to make the live demo better?

**Comment by Xinyu-Yi** [comment]
Yes, it will be affected by magnetic field. You should perform magnetic calibration for all your IMUs together before using PIP. Typically, this is achieved by rotating the sensors in all directions (e.g. drawing 8). This should be provided by the IMU manufacturer.
