### ISSUE TITLE
some questions about process_amass in preprocess.py

### ISSUE THREAD

**Issue by huzijun1996** [Xinyu-Yi/PIP#24]
Hi, 
I have preprocessed the ACCAD/Male2General_c3d/A6- Box lift_poses.npz in the AMASS dataset according to your method.I found that after deploying the actions in the DIP-IMU dataset in Unity first, then putting the actions in the AMASS dataset into Unity will result in a flipped situation. The first picture is the situation after inputting data directly into unity, the second picture is the situation after inputting pre-processed data into unity, and the third picture is the official render provided by AMASS, is this considered as "align AMASS global frame with DIP"? Is this pre-processing effect correct? (The fourth figure shows the direct import of the DIP dataset s_10/01_a.pkl into unity.)
If the DIP and AMASS datasets cannot be in the same global framework, I am afraid it will affect the training and testing of the neural network.

![1预处理前](https://github.com/Xinyu-Yi/PIP/assets/56211942/19c50929-d21b-4213-aeef-f510f95c4d11)

![2预处理后](https://github.com/Xinyu-Yi/PIP/assets/56211942/06bbcb40-2d61-44c0-a5e7-7d05d64f4284)

![3Picture3](https://github.com/Xinyu-Yi/PIP/assets/56211942/ab0aebf8-27dd-4702-9ec6-c052326007a6)

![4DIP-IMU](https://github.com/Xinyu-Yi/PIP/assets/56211942/1a822d11-2fa7-4dbb-8f06-d33987b6389c)

**Comment by Xinyu-Yi** [comment]
Yes, you need to "align AMASS global frame with DIP". I remember I have left-multiplied a matrix with all entries 1 or 0 to the AMASS global rotation/translation in the preprocessing script. That matrix will rotate AMASS into a y-up coordinate.

**Comment by Xinyu-Yi** [comment]
Oh, its in Transpose/preprocess.py in Line 64. You can check the "Transpose" repository

**Comment by Xinyu-Yi** [comment]
I'm sorry. PIP also has the code, in Line 65 in preprocess.py

**Comment by huzijun1996** [comment]
Yes, I just preprocessed the AMASS dataset as you did in your code, but  after processing, I put the data into unity and the second image  appears, is this considered successful preprocessing? (Putting preprocessed AMASS  data into unity is back to me, while putting dip-imu data into unity in  the same case is frame to me)



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xinyu ***@***.***&gt;; 
发送时间: 2023年6月27日(星期二) 晚上9:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xinyu-Yi/PIP] some questions about process_amass in preprocess.py (Issue #24)





 
I'm sorry. PIP also has the code, in Line 65 in preprocess.py

**Comment by huzijun1996** [comment]
Yes, I just preprocessed the AMASS dataset as in your code, but after processing, I put the data into unity and the second picture appears, is this a successful preprocessing? (Putting AMASS data into unity is back to me, while putting dip-imu data into unity in the same case is front to me)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xinyu ***@***.***&gt;; 
发送时间: 2023年6月27日(星期二) 晚上9:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xinyu-Yi/PIP] some questions about process_amass in preprocess.py (Issue #24)





 
I'm sorry. PIP also has the code, in Line 65 in preprocess.py

**Comment by huzijun1996** [comment]
> Oh, its in Transpose/preprocess.py in Line 64. You can check the "Transpose" repository



> I'm sorry. PIP also has the code, in Line 65 in preprocess.py

I have processed the data accordingly according to your method, and after putting the data in the processed AMASS dataset and the data in the original DIP-IMU dataset into unity, the pose in the DIP-IMU dataset is facing me, and the pose in the AMASS dataset is back to me, is this considered to have completed the preprocessing?(The attitude in the DIP-IMU dataset is shown in Figure 4, and the attitude in the processed AMASS dataset is shown in Figure 2)

**Comment by huzijun1996** [comment]
> Oh, its in Transpose/preprocess.py in Line 64. You can check the "Transpose" repository



> I'm sorry. PIP also has the code, in Line 65 in preprocess.py

I have processed the data accordingly according to your method, and after putting the data in the processed AMASS dataset and the data in the original DIP-IMU dataset into unity3D, the pose in the DIP-IMU dataset is facing me, and the pose in the AMASS dataset is back to me, is this considered to have completed the preprocessing?(The attitude in the DIP-IMU dataset is shown in Figure 4, and the attitude in the processed AMASS dataset is shown in Figure 2)

**Comment by huzijun1996** [comment]
> > Oh, its in Transpose/preprocess.py in Line 64. You can check the "Transpose" repository
> 
> > I'm sorry. PIP also has the code, in Line 65 in preprocess.py
> 
> I have processed the data accordingly according to your method, and after putting the data in the processed AMASS dataset and the data in the original DIP-IMU dataset into unity3D, the pose in the DIP-IMU dataset is facing me, and the pose in the AMASS dataset is back to me, is this considered to have completed the preprocessing?(The attitude in the DIP-IMU dataset is shown in Figure 4, and the attitude in the processed AMASS dataset is shown in Figure 2)

The pose given in the official AMASS render is shown in Figure 3.

**Comment by Xinyu-Yi** [comment]
If you process correctly, y-axis will be the up direction

**Comment by huzijun1996** [comment]
> If you process correctly, y-axis will be the up direction

Yes, I have followed the method you provided earlier and the y-axis is already directed upwards, but it seems that the y-axis is rotated and does not have the character model facing me as in the official render, is this pre-processing successful? Or do I need some further processing to make the model no longer turn its back to me?

**Comment by huzijun1996** [comment]
> If you process correctly, y-axis will be the up direction

After preprocessing as you did, the video that appears in unity3D is shown below:

https://github.com/Xinyu-Yi/PIP/assets/56211942/7d8360fe-3054-4f57-8643-9332a8a197f9

**Comment by huzijun1996** [comment]
> If you process correctly, y-axis will be the up direction

After preprocessing as you did, the video that appears in unity3D is shown below:(it always turns its back to me)


https://github.com/Xinyu-Yi/PIP/assets/56211942/66c1d98d-51ae-4c60-bdc4-4bf48b59e16a

**Comment by Xinyu-Yi** [comment]
I think that doesn't matter. There are many motions that the subject walks and turns around. You should keep the y-axis's rotation.

**Comment by huzijun1996** [comment]
> I think that doesn't matter. There are many motions that the subject walks and turns around. You should keep the y-axis's rotation.

But the official render is facing me directly without rotation (as shown below), can these two situations be considered the same? Or do I need to rotate the coordinate axis on the basis of the pre-processing you give, so that the Mannequin changes from being back to me to facing me?

https://github.com/Xinyu-Yi/PIP/assets/56211942/d798d9cc-d7db-4fbf-a5db-9d17a1cc8ddc

**Comment by Xinyu-Yi** [comment]
I see. It will not affect the training and testing. Maybe you can place the camera on the other side of the human in Unity to render the pose,
