### ISSUE TITLE
GRF value is empty

### ISSUE THREAD

**Issue by visonpon** [Xinyu-Yi/PIP#25]
Hi @Xinyu-Yi ,thanks for sharing this wonderful work. I tried to get the GRF form [this line](https://github.com/Xinyu-Yi/PIP/blob/0e8df58d3b67ac5922626d72e9d6b74a068df108/dynamics.py#L230),
`qddot = x[:self.model.qdot_size]
 GRF = x[self.model.qdot_size:-self.model.qdot_size]
tau = x[-self.model.qdot_size:]`
my x's shape is 150 and the qdot_size=75, so the GRF is an empty index range. Is there some details I ignored, hope you can help, thank you.

**Comment by Xinyu-Yi** [comment]
This means that no foot contacts, therefore no grf
