### ISSUE TITLE
手一直保持T形

### ISSUE THREAD

**Issue by lecomet** [Xinyu-Yi/PIP#27]
我使用的是Noitom Pro传感器。无论我使用Transpose还是PIP算法 估计后的人体姿态 上半身一直呈现T形 有轻微的动作  下半身动作没啥问题 请问这是算法问题还是传感器数据问题

**Comment by Xinyu-Yi** [comment]
检查一下小臂和头部imu的输出，是否有测量值

**Comment by lecomet** [comment]
小臂和头部imu的输出是有测量值的 如下所示：
Head-Sensor-Acce-x | Head-Sensor-Acce-y | Head-Sensor-Acce-z-- | -- | --
0.00437178 | -0.00289547 | 0.00218686
-0.000388127 | -0.00570482 | 0.00570597
-0.0102392 | 0.00576174 | 0.00866639
-0.00413198 | -0.00464767 | 0.00942544
0.00287678 | 0.00394559 | 0.00545922
0.00677366 | 0.00676084 | 0.00234542
0.00552812 | 0.0106499 | -0.0056192
0 | 0 | 0
0.0105158 | -0.0128654 | 0.00120484
0.00331823 | -0.0166366 | -0.00163424
0.00659488 | -0.0137587 | 0.0051849
0.00384355 | -0.00227463 | -0.00305232
0 | 0 | 0
0.00972971 | 0.0129804 | -0.00279937
-0.000911457 | -0.00511944 | 0.00163502
0.00311297 | -0.0110188 | 0.00742644
0.00472745 | 0.0170186 | 0.00659978
0.0142103 | 0.00293177 | 0.00255693
0.00995665 | 0.00277519 | 0.00584516
0.00751578 | 0.0123093 | 0.00336569
0.00881801 | 0.0169198 | 0.00242257
0.00730065 | 0.0091235 | 0.00144642
0.00855097 | -0.000864804 | 0.00657231
0.0117932 | -0.000735223 | -0.00370491
0.0202855 | 0.00983244 | -0.0119237
0.0307617 | 0.0220553 | -0.0266352
0.0172086 | 0.0130284 | -0.0187611
0.0078077 | -0.00703931 | -0.00720425
-0.0068443 | -0.0253312 | 0.00170484
-0.0177717 | -0.0262987 | 0.0138521
-0.0165614 | -0.0135409 | 0.0141432
-0.0123831 | -0.0077219 | 0.00657747
-0.00686999 | 3.34E-06 | 0.00156432
-0.00135333 | 0.0111526 | 0.000702392
-0.000108561 | 0.01289 | 0.00137886
-0.0063569 | -0.00142664 | 0.00989615
-0.0055204 | 0.0127047 | 0.00554823
-0.00394277 | -0.00233477 | -0.00327673

**Comment by Xinyu-Yi** [comment]
你这个加速度全是0啊
