### ISSUE TITLE
How dd you evaluate the performance of pip without physics-based optimizer

### ISSUE THREAD

**Issue by drlxj** [Xinyu-Yi/PIP#28]
Hi,

I want to evaluate performance without the physics-based optimizer, particularly to assess its impact on positional accuracy.  Thus, in your code, I replace pose_opt with the pose variable calculated in line 93, but couldn't find the replacement for tran_opt. Could you provide more details on the implementation of the ablation study? Thanks.

![Screenshot from 2023-07-22 14-59-52](https://github.com/Xinyu-Yi/PIP/assets/83223416/2d7181c4-4ae4-49d7-9261-eae9e29cf21e)

**Comment by Xinyu-Yi** [comment]
Yes, you can directly use "pose" to replace "pose_opt". But the network did not estimate translation, so there is nothing you can replace "tran_opt" with. If you want an approximate estimation, you may integrate the "joint_velocity" and discard all non-root joints' velocity. But that will lead to significant foot sliding as physics is not applied.

**Comment by Xinyu-Yi** [comment]
The translation is calculated in the physics module by leveraging all joints' velocity, contacts, pose, and physics.
