### ISSUE TITLE
pytorch version of dip

### ISSUE THREAD

**Issue by Jaceyxy** [Xinyu-Yi/PIP#29]
Hi， I hope you are well. I am working on a project that uses the DIP model. I am more familiar with PyTorch and was wondering if you have a PyTorch version of the DIP model that you could share with me. This would be greatly appreciated.My email is yxy2535287050@gmail.com
Thank you in advance for your help！！

**Comment by Xinyu-Yi** [comment]
Sorry, I don't have a pytorch-version DIP model. I just run the official code to get their results.
