### ISSUE TITLE
rbdl with Python bindings for Windows

### ISSUE THREAD

**Issue by NoLoPhe** [Xinyu-Yi/PIP#3]
Hi @Xinyu-Yi 

I can't build rbdl with Python bindings for Windows
Please write a instruction to import rbdl

Thank you!

**Comment by NoLoPhe** [comment]
From [Issuse](https://github.com/bulletphysics/bullet3/issues/2246), I noticed that it is possible to use pybullet functions to replace rbdl.

```
import rbdl
import pybullet as pb

# loadModel
rbdlmodel = rbdl.loadModel(path_to_urdf)
pbmodel = pb.loadURDF(path_to_urdf, useFixedBase=True, flags = pb.URDF_USE_INERTIA_FROM_FILE)

# InverseDynamics
rbdl.InverseDynamics(rbdlmodel, q_rbdl, zeros_rbdl, zeros_rbdl, tau_rbdl)
tau_pb = pb.calculateInverseDynamics(pbmodel, q_pb, zeros_pb, zeros_pb)
```

**Comment by SlimeVRX** [comment]
## Try for Linux

From @[flxalr](https://github.com/eurobench/eb_hum_bench/blob/master/Dockerfile)

```
# Install rbdl-org dependencies

apt-get -qq install --no-install-recommends -y build-essential cmake && \
apt-get -qq install --no-install-recommends -y git-core libeigen3-dev && \
apt-get -qq install --no-install-recommends -y cmake-curses-gui lua5.1 liblua5.1-0-dev

apt-get -qq install --no-install-recommends -y cython3 && \
apt-get -qq install --no-install-recommends -y python3-numpy && \
apt-get -qq install --no-install-recommends -y python3-matplotlib && \
apt-get -qq install --no-install-recommends -y python3-scipy && \
apt-get -qq install --no-install-recommends -y python3-pytest

apt-get -qq install --no-install-recommends libboost-all-dev
apt-get -qq install --no-install-recommends -y git
git clone https://gitlab.com/flxalr/rbdl_balance.git /home/pi_runner/rbdl-orb

mkdir -p /home/pi_runner/rbdl-orb-build
cd /home/pi_runner/rbdl-orb-build && \
    cmake -D CMAKE_BUILD_TYPE=Release -D RBDL_BUILD_ADDON_LUAMODEL=ON \
    -D RBDL_BUILD_ADDON_URDFREADER=ON -D RBDL_BUILD_ADDON_BALANCE=ON \
    -D RBDL_BUILD_PYTHON_WRAPPER=ON ../rbdl-orb
cd /home/pi_runner/rbdl-orb-build && \
    make

# Export

PYTHONPATH=${PYTHONPATH}:/home/pi_runner/rbdl-orb-build/python
export PYTHONPATH=${PYTHONPATH}:/home/pi_runner/.local/bin

# Add articulate/utils/rbdl/model.py

import sys
sys.path.insert(0, "/home/pi_runner/rbdl-orb-build/python")

import rbdl
```

**Comment by SlimeVRX** [comment]
![Screenshot from 2022-07-05 22-02-27](https://user-images.githubusercontent.com/99313947/177358686-7fa093df-1a92-4bd5-b9f8-6579c22cd595.png)

**Comment by mariolew** [comment]
@NoLoPhe Hi, I'd like to know how to use rbdl on windows

**Comment by NoLoPhe** [comment]
Hi @mariolew!
I still can't do it right now, I'm learning C++.

**Comment by NoLoPhe** [comment]
Reference from rbld-old version

Windows binding generator to wrap C++ for Python using Pybind11 from @[erwincoumans](https://github.com/erwincoumans/rbdl)

```
git clone https://github.com/erwincoumans/rbdl.git
python setup.py install
```

**Comment by mariolew** [comment]
@NoLoPhe 

> 

I successfully built the python binding using @[erwincoumans](https://github.com/erwincoumans/rbdl)'s copy. I'm not sure whether the name of the methods are the same as the version used in PIP. However, PIP can be used under rbdl v2.6.0.

**Comment by mariolew** [comment]
@NoLoPhe The interface is different.

**Comment by NoLoPhe** [comment]
Hi @mariolew!

I have tried and confirmed rbdl v2.6.0 (@erwincoumans version) can be used in PIP (Linux) with **CMAKE.**

You have to change a bit to be able to build with python3 instead of python2.

```
git clone https://github.com/erwincoumans/rbdl.git /home/pi_runner/rbdl-orb

mkdir -p /home/pi_runner/rbdl-orb-build
cd /home/pi_runner/rbdl-orb-build && \
    cmake -D CMAKE_BUILD_TYPE=Release -D RBDL_BUILD_ADDON_LUAMODEL=ON \
    -D RBDL_BUILD_ADDON_URDFREADER=ON -D RBDL_BUILD_ADDON_BALANCE=ON \
    -D RBDL_BUILD_PYTHON_WRAPPER=ON ../rbdl-orb
cd /home/pi_runner/rbdl-orb-build && \
    make
```

I am trying to be able to use v2.6.0 version in Windows.

**Comment by mariolew** [comment]
@NoLoPhe https://github.com/erwincoumans/rbdl/blob/master/python/pyrbdl.cc from this file you can see that the python interface is different. This file should be modified or it cannot be used in PIP.

**Comment by NoLoPhe** [comment]
@mariolew Yes, must be modified. Wait for me, I'm trying another way.

**Comment by mariolew** [comment]
@NoLoPhe OK

**Comment by NoLoPhe** [comment]
> 



> Hi @mariolew!
> 
> I have tried and confirmed rbdl v2.6.0 (@erwincoumans version) can be used in PIP (Linux) with **CMAKE.**
> 
> You have to change a bit to be able to build with python3 instead of python2.
> 
> ```
> git clone https://github.com/erwincoumans/rbdl.git /home/pi_runner/rbdl-orb
> 
> mkdir -p /home/pi_runner/rbdl-orb-build
> cd /home/pi_runner/rbdl-orb-build && \
>     cmake -D CMAKE_BUILD_TYPE=Release -D RBDL_BUILD_ADDON_LUAMODEL=ON \
>     -D RBDL_BUILD_ADDON_URDFREADER=ON -D RBDL_BUILD_ADDON_BALANCE=ON \
>     -D RBDL_BUILD_PYTHON_WRAPPER=ON ../rbdl-orb
> cd /home/pi_runner/rbdl-orb-build && \
>     make
> ```
> 
> I am trying to be able to use v2.6.0 version in Windows.

After checking again, I discovered the error.

Not:
git clone https://github.com/erwincoumans/rbdl.git
True: 
git clone https://github.com/erwincoumans/rbdl_old.git

Both versions are from **Erwincoumans** and both are **v2.6.0**

**Comment by mariolew** [comment]
@NoLoPhe  Yeah, rbdl_old is the same as the official rbdl v2.6.0, but it is hard to be installed on windows.

**Comment by NoLoPhe** [comment]
Hi @Xinyu-Yi and @mariolew!

I want to announce the good news that I have deployed **PIP** on Windows.
Thanks for the work from @erwincoumans with RBDL python bindings (Pybind11). I started learned more C++ and customized his source.

![image](https://user-images.githubusercontent.com/60751518/184347936-daa7a549-819f-4788-b73e-9570af2dfaf7.png)

**Comment by NoLoPhe** [comment]
Modified code I updated here: [PIP](https://github.com/SlimeVRX/PIP), [RBDL](https://github.com/SlimeVRX/rbdl)

Test environment in Pycharm: 
- [Python-3.9](https://www.python.org/ftp/python/3.9.10/python-3.9.10-amd64.exe)
- [Torch-1.9.1+cpu](https://download.pytorch.org/whl/cpu/torch-1.9.1%2Bcpu-cp39-cp39-win_amd64.whl)
- [Torchvision-0.10.1+cpu](https://download.pytorch.org/whl/cpu/torchvision-0.10.1%2Bcpu-cp39-cp39-win_amd64.whl)

PIP: **Install correct version in requirements.txt**
```
git clone https://github.com/SlimeVRX/PIP.git
pip install "torch-1.9.1+cpu-cp39-cp39-win_amd64.whl"
pip install "torchvision-0.10.1+cpu-cp39-cp39-win_amd64.whl"
pip install -r requirements.txt
```
RBDL:
```
git clone https://github.com/SlimeVRX/rbdl.git
python setup.py install
```
If having problems with the library version, check **pip list**:
```
Package              Version
-------------------- -----------
anyio                3.6.1      
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.7
attrs                22.1.0
Babel                2.10.3
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               5.0.1
certifi              2022.6.15
cffi                 1.15.1
charset-normalizer   2.1.0
chumpy               0.70
colorama             0.4.5
cvxopt               1.3.0
cycler               0.11.0
debugpy              1.6.2
decorator            5.1.1
defusedxml           0.7.1
deprecation          2.1.0
entrypoints          0.4
executing            0.9.1
fastjsonschema       2.16.1
fonttools            4.34.4
h5py                 3.7.0
idna                 3.3
imageio              2.21.1
importlib-metadata   4.12.0
ipykernel            6.15.1
ipython              8.4.0
ipython-genutils     0.2.0
ipywidgets           7.7.1
jedi                 0.18.1
Jinja2               3.1.2
json5                0.9.9
jsonschema           4.9.1
jupyter-client       7.3.4
jupyter-core         4.11.1
jupyter-packaging    0.12.2
jupyter-server       1.18.1
jupyterlab           3.4.5
jupyterlab-pygments  0.2.2
jupyterlab-server    2.15.0
jupyterlab-widgets   1.1.1
kiwisolver           1.4.4
lxml                 4.9.1
MarkupSafe           2.1.1
matplotlib           3.5.3
matplotlib-inline    0.1.3
mistune              0.8.4
nbclassic            0.4.3
nbclient             0.6.6
nbconvert            6.5.3
nbformat             5.4.0
nest-asyncio         1.5.5
notebook             6.4.12
notebook-shim        0.1.0
numpy                1.23.1
open3d               0.15.1
opencv-python        4.6.0.66
packaging            21.3
pandocfilters        1.5.0
parso                0.8.3
pickleshare          0.7.5
Pillow               9.2.0
pip                  21.3.1
prometheus-client    0.14.1
prompt-toolkit       3.0.30
psutil               5.9.1
pure-eval            0.2.2
pybullet             3.2.5
pycparser            2.21
Pygments             2.12.0
pyparsing            3.0.9
pyrbdl               0.0.2
pyrsistent           0.18.1
python-dateutil      2.8.2
pytz                 2022.2
pywin32              304
pywinpty             2.0.7
pyzmq                23.2.1
qpsolvers            1.8.0
quadprog             0.1.11
requests             2.28.1
scipy                1.9.0
Send2Trash           1.8.0
setuptools           60.2.0
six                  1.16.0
sniffio              1.2.0
soupsieve            2.3.2.post1
stack-data           0.3.0
terminado            0.15.0
tinycss2             1.1.1
tomlkit              0.11.3
torch                1.9.1+cpu
torchvision          0.10.1+cpu
tornado              6.2
tqdm                 4.64.0
traitlets            5.3.0
transforms3d         0.3.1
typing_extensions    4.3.0
urllib3              1.26.11
vctoolkit            0.1.5.39
wcwidth              0.2.5
webencodings         0.5.1
websocket-client     1.3.3
wheel                0.37.1
widgetsnbextension   3.6.1
zipp                 3.8.1
```

**Comment by mariolew** [comment]
@NoLoPhe  Really cool! I'm trying now.

**Comment by zhuzejun** [comment]
> Modified code I updated here: [PIP](https://github.com/SlimeVRX/PIP), [RBDL](https://github.com/SlimeVRX/rbdl)
> 
> Test environment in Pycharm:
> 
> * [Python-3.9](https://www.python.org/ftp/python/3.9.10/python-3.9.10-amd64.exe)
> * [Torch-1.9.1+cpu](https://download.pytorch.org/whl/cpu/torch-1.9.1%2Bcpu-cp39-cp39-win_amd64.whl)
> * [Torchvision-0.10.1+cpu](https://download.pytorch.org/whl/cpu/torchvision-0.10.1%2Bcpu-cp39-cp39-win_amd64.whl)
> 
> PIP: **Install correct version in requirements.txt**
> 
> ```
> git clone https://github.com/SlimeVRX/PIP.git
> pip install "torch-1.9.1+cpu-cp39-cp39-win_amd64.whl"
> pip install "torchvision-0.10.1+cpu-cp39-cp39-win_amd64.whl"
> pip install -r requirements.txt
> ```
> 
> RBDL:
> 
> ```
> git clone https://github.com/SlimeVRX/rbdl.git
> python setup.py install
> ```
> 
> If having problems with the library version, check **pip list**:
> 
> ```
> Package              Version
> -------------------- -----------
> anyio                3.6.1      
> argon2-cffi          21.3.0
> argon2-cffi-bindings 21.2.0
> asttokens            2.0.7
> attrs                22.1.0
> Babel                2.10.3
> backcall             0.2.0
> beautifulsoup4       4.11.1
> bleach               5.0.1
> certifi              2022.6.15
> cffi                 1.15.1
> charset-normalizer   2.1.0
> chumpy               0.70
> colorama             0.4.5
> cvxopt               1.3.0
> cycler               0.11.0
> debugpy              1.6.2
> decorator            5.1.1
> defusedxml           0.7.1
> deprecation          2.1.0
> entrypoints          0.4
> executing            0.9.1
> fastjsonschema       2.16.1
> fonttools            4.34.4
> h5py                 3.7.0
> idna                 3.3
> imageio              2.21.1
> importlib-metadata   4.12.0
> ipykernel            6.15.1
> ipython              8.4.0
> ipython-genutils     0.2.0
> ipywidgets           7.7.1
> jedi                 0.18.1
> Jinja2               3.1.2
> json5                0.9.9
> jsonschema           4.9.1
> jupyter-client       7.3.4
> jupyter-core         4.11.1
> jupyter-packaging    0.12.2
> jupyter-server       1.18.1
> jupyterlab           3.4.5
> jupyterlab-pygments  0.2.2
> jupyterlab-server    2.15.0
> jupyterlab-widgets   1.1.1
> kiwisolver           1.4.4
> lxml                 4.9.1
> MarkupSafe           2.1.1
> matplotlib           3.5.3
> matplotlib-inline    0.1.3
> mistune              0.8.4
> nbclassic            0.4.3
> nbclient             0.6.6
> nbconvert            6.5.3
> nbformat             5.4.0
> nest-asyncio         1.5.5
> notebook             6.4.12
> notebook-shim        0.1.0
> numpy                1.23.1
> open3d               0.15.1
> opencv-python        4.6.0.66
> packaging            21.3
> pandocfilters        1.5.0
> parso                0.8.3
> pickleshare          0.7.5
> Pillow               9.2.0
> pip                  21.3.1
> prometheus-client    0.14.1
> prompt-toolkit       3.0.30
> psutil               5.9.1
> pure-eval            0.2.2
> pybullet             3.2.5
> pycparser            2.21
> Pygments             2.12.0
> pyparsing            3.0.9
> pyrbdl               0.0.2
> pyrsistent           0.18.1
> python-dateutil      2.8.2
> pytz                 2022.2
> pywin32              304
> pywinpty             2.0.7
> pyzmq                23.2.1
> qpsolvers            1.8.0
> quadprog             0.1.11
> requests             2.28.1
> scipy                1.9.0
> Send2Trash           1.8.0
> setuptools           60.2.0
> six                  1.16.0
> sniffio              1.2.0
> soupsieve            2.3.2.post1
> stack-data           0.3.0
> terminado            0.15.0
> tinycss2             1.1.1
> tomlkit              0.11.3
> torch                1.9.1+cpu
> torchvision          0.10.1+cpu
> tornado              6.2
> tqdm                 4.64.0
> traitlets            5.3.0
> transforms3d         0.3.1
> typing_extensions    4.3.0
> urllib3              1.26.11
> vctoolkit            0.1.5.39
> wcwidth              0.2.5
> webencodings         0.5.1
> websocket-client     1.3.3
> wheel                0.37.1
> widgetsnbextension   3.6.1
> zipp                 3.8.1
> ```

Hi，NoLoPhe,I encountered the problem"WARNING: Requirement 'torch-1.9.1+cpu-cp39-cp39-win_amd64.whl' looks like a filename, but the file does not exist
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: torch-1.9.1+cpu-cp39-cp39-win_amd64.whl is not a supported wheel on this platform." when I excuted the 
cmd "pip install "torch-1.9.1+cpu-cp39-cp39-win_amd64.whl"",do you know what's the problem,thank you,my python   version is 3.8.5. @NoLoPhe

**Comment by SlimeVRX** [comment]
- Need python 3.9 (not 3.8.5)
- Need System Architecture Win_amd64
- Torch-1.9.1 you can download [here](https://download.pytorch.org/whl/cpu/torch-1.9.1%2Bcpu-cp39-cp39-win_amd64.whl#sha256=991b6ac3d1772da80059e477c864f9fa2ffbeb7794c6473a1644e25c61d2ee56)

**Comment by zhuzejun** [comment]
收到，我将查看后进行回复。

**Comment by zhuzejun** [comment]
> * Need python 3.9 (not 3.8.5)
> * Need System Architecture Win_amd64
> * Torch-1.9.1 you can download [here](https://download.pytorch.org/whl/cpu/torch-1.9.1%2Bcpu-cp39-cp39-win_amd64.whl#sha256=991b6ac3d1772da80059e477c864f9fa2ffbeb7794c6473a1644e25c61d2ee56)

thank you,and now I don't know the raw_amass_dir and raw_totalcapture_dip_dir and raw_totalcapture_official_dir how can I get,and I have got the DIP author who has provided account to me,but I don't know which link can download and AMASS how can get,would you please help guide me,thank a lot!!
@SlimeVRX  <img width="578" alt="1708418708099" src="https://github.com/Xinyu-Yi/PIP/assets/25922893/a8368193-4803-4cad-8b41-719f88c2faf0">

**Comment by SlimeVRX** [comment]
Please add my WeChat
![image](https://github.com/Xinyu-Yi/PIP/assets/99313947/96615e13-9a20-4d18-b064-0e827a8963ba)

**Comment by whl-007** [comment]
> Hi @Xinyu-Yi
> 
> I can't build rbdl with Python bindings for Windows Please write a instruction to import rbdl
> 
> Thank you!
> 
> 
> Hi@ Xinyu Yi
> 
> 我无法使用Python绑定为Windows构建rbdl 请编写导入rbdl的说明
> 
> 谢谢你，谢谢
I have encountered the problem 'module 'rbdl' has no attribute 'loadModel'. Have you solved this issue? If you could help me solve this problem, I would be greatly appreciated.
