### ISSUE TITLE
能否提供Unity四肢数据可视化demo

### ISSUE THREAD

**Issue by jiky** [Xinyu-Yi/PIP#30]
能够提供带有四肢数据可视化效果的Unity Demo
<img width="533" alt="image" src="https://github.com/Xinyu-Yi/PIP/assets/3060568/e0912d2e-df9d-41c8-8c0b-3ccd213483f6">

**Comment by Xinyu-Yi** [comment]
这个找不到了，当时使用skinning weights 写的，但是unity里模型顶点要多于6890，需要自己处理一下
