### ISSUE TITLE
复现Noitom实验的时候的两个小问题

### ISSUE THREAD

**Issue by jun951113** [Xinyu-Yi/PIP#31]
您好作者，我在尝试复现您的noitom实验的时候有几个小问题想问您一下：1. 现在的前向运动学模型是直接调用smpl模型，但smpl模型每个模型的bone length固定，如何更改骨骼长度​？transpose里面是通过FK求的下肢坐标所以可以更改，PIP这里也能更改么？ ​2. 为什么坐下去后抬腿的话整个人会降到地面上去？ 期待您的回复~谢谢

**Comment by Xinyu-Yi** [comment]
1 可以自己实现forward kinematics，使用不同的骨骼长度。默认的是使用zero shape的骨骼长度
2 因为整个场景假设是地面，物理模拟里重力会把人拉下去

**Comment by jun951113** [comment]
> 
不好意思我能问一下，针对问题1，您的意思是对神经网络部分输出的结果做forward kinematics，还是在physics constrain部分做forward kinematics呀

**Comment by Xinyu-Yi** [comment]
哦我想了一下可能还不是那么简单，要改物理模型。

**Comment by jun951113** [comment]
> 哦我想了一下可能还不是那么简单，要改物理模型。

您好~就是要在物理模型那块进行更改，前向运动学那边没办法更改是么
