### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by alchemyam** [Xinyu-Yi/PIP#32]
I am trying to apply it to your project by using a sensor from another company other than xsens or noitom.

![image](https://github.com/Xinyu-Yi/PIP/assets/142787506/25c60706-0df3-401a-a1b1-af605dad2854)

An error occurred when evaluator.py was executed, so I finished learning after commenting out lines 183-184 and 190-191. When I ran the live demo, it moved like the attached GIF. Did the commenting affect the quality? If not, do you know what could be the cause?

![ezgif com-video-to-gif](https://github.com/Xinyu-Yi/PIP/assets/142787506/c9997843-f267-47f3-93cf-a6ad172ebdf3)

I simply moved my arm up and down, but looking at the GIF image, the character's arm movement is unnatural and wavy.

development environment
 - CPU : i7-10700
 - GPU : NVIDIA Geforce RTX 3080Ti
 - RAM : 64GB

The development environment of my PC is as described above.

I ran the Unity Live Demo project to test the real-time movement of the character.
When I run 'live demo_xx.py', it is only 30 fps.
It uses 100% of the CPU and the reaction speed is very slow. 

What minimum specifications should be required to run smoothly?

Can't both CPU and GPU be used for computation?

**Comment by Xinyu-Yi** [comment]
The codes you comment out should not affect the performance. You can comment out those.

The QP solver can only run on CPU. It seems that your sensor fps is even lower than 30, which may cause this problem. You may comment out the physics part and check if the pose is correct. To achieve this, at line 135 in net.py, return the pose and a [0,0,0] translation

**Comment by Xinyu-Yi** [comment]
Then your performance should be higher than 60fps. Please check if the pose is correct. If yes, then maybe you need to update the computer or run it offline.

**Comment by alchemyam** [comment]
The sensor I'm testing can update data at up to 100Hz.

However, if you update the data at 100Hz, the update rate of the character is very slow.

So, the attached GIF is what I updated the 30Hz data by adjusting the update rate of the sensor data.

If you update at a faster rate than this, your character's update rate will start to slow down.

Considering that the cpu is using 100%, I think the CPU operation speed cannot keep up with the sensor data update speed.

Please tell us the specifications of the CPU you are using.

**Comment by Xinyu-Yi** [comment]
i7-12xxx

**Comment by Xinyu-Yi** [comment]
As the network assumes 60-fps acceleration input, if your input rate is only 30 fps, I think the results will be bad for internal joints.

**Comment by Xinyu-Yi** [comment]
Maybe you can also try to move the network part to GPU. But in my experiment, the network is very fast compared with the physics optimization, which can only run on CPU.

**Comment by alchemyam** [comment]
I would like to purchase and follow the noitom sensor you used. Is the sensor you used 'AxisStudio' or 'Perception Neuron 3'?

Also, can I download and use the 'Axis Studio 2.1' program?

**Comment by alchemyam** [comment]
![image](https://github.com/Xinyu-Yi/PIP/assets/142787506/083e26d5-8475-44a3-afc2-2024ad0ba2a8)

I purchased PN3, downloaded and ran Axis Studio 2.11. In the Settings menu, I set it as shown in the picture. Did I do it correctly? Is it right to transmit BVH?
