### ISSUE TITLE
Ask for help for lift leg

### ISSUE THREAD

**Issue by jun951113** [Xinyu-Yi/PIP#36]
Hi Xinyu,

Nice Project! I have a little question for trying to use my own IMU to test PIP, I cannot lift leg for 90 degree like this video:
![image](https://github.com/Xinyu-Yi/PIP/assets/40925081/1a4cce1d-7dbf-4188-9da5-5604023ba555)

I am wondering if you can please give me some advice for this problem?

Thanks!

**Comment by Xinyu-Yi** [comment]
Please check if you have input the correct accelerations: in m/s^2, in the global frame, g=9.8 removed

**Comment by Xinyu-Yi** [comment]
I think it would be easy to lift the leg to about 60-80 degrees. However, if you lift the leg and do plenty of motions like jumping, turning around, which makes much acceleration on the sensors, the leg will not be tracked accurately. It will still suffer from ambiguity.
