### ISSUE TITLE
'module 'rbdl' has no attribute 'loadModel'

### ISSUE THREAD

**Issue by whl-007** [Xinyu-Yi/PIP#37]
I have encountered the problem 'module 'rbdl' has no attribute 'loadModel'. Have you solved this issue? If you could help me solve this problem, I would be greatly appreciated.

**Comment by Recialhot** [comment]
Hello, I have also encountered this problem. Have you resolved it

**Comment by whl-007** [comment]
> Hello, I have also encountered this problem. Have you resolved it

yes，you can try like this link：https://blog.csdn.net/apple_74181154/article/details/135559631?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2~default~CTRLIST~Rate-1-135559631-blog-123514200.235%5Ev43%5Epc_blog_bottom_relevance_base4&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2~default~CTRLIST~Rate-1-135559631-blog-123514200.235%5Ev43%5Epc_blog_bottom_relevance_base4&utm_relevant_index=2
