### ISSUE TITLE
Questions on training dataset

### ISSUE THREAD

**Issue by funnyQZQ** [Xinyu-Yi/PIP#4]
As mentioned in paper, you train the neural kinematics estimator with AMASS dataset. How to get the gt joint velocity from AMASS dataset? Just smpl_joint(t) - smpl_joint(t - 1)?

**Comment by Xinyu-Yi** [comment]
Yes. Just calculate the joint position in the global space and use finite difference to compute the velocity. Then transform the velocity to the root space. Please see appendix A in the paper.

**Comment by drlxj** [comment]
Another question about the training dataset: how to get the gt foot-ground contact from AMASS dataset?

**Comment by Xinyu-Yi** [comment]
> Another question about the training dataset: how to get the gt foot-ground contact from AMASS dataset?

You can find this in the paper: a foot that has a low velocity is labeled as in contact
