### ISSUE TITLE
Is there a designated wearing direction for the DOT sensor?

### ISSUE THREAD

**Issue by wookjin** [Xinyu-Yi/PIP#45]
hello.

I am the one who purchased the Xsens DOT sensor and am following your research. 

Thank you very much for revealing this.

DOT was worn on the body.

It was worn on the wrist, below the knee, and behind the waist.

The wearing direction was such that the sensor light was directed upward.

Quaternion and FreeAcceleration values ​​are saved and loaded using the Movella DOT application.

But it doesn't move like the video you posted. 

Is the wearing direction or attachment location of the sensor important?

In the case of the leg, does it have to be attached to the inside of the shin bone?

Do I need to Reset Heading in the Movella DOT application?? 

I've tried everything, but it doesn't work as shown in the video, so I'm asking a question.

@Xinyu-Yi

**Comment by wookjin** [comment]
![image](https://github.com/user-attachments/assets/21aa1bc7-a568-42e1-9812-f8c54e0778e3)


It was attached to a mannequin for illustration purposes. Is it worn in the correct area and direction?

**Comment by Xinyu-Yi** [comment]
Hi, the wearing positions matter, but the orientation can be arbitrary. For the xsens dot, heading reset is needed as it runs a 6-axis algorithm though it is a 9-axis sensor. 

So the calibration step is 3-step:
1. Align all sensors' heading and perform heading reset
2. Use one sensor to determine the human heading
3. Keep the heading and perform T pose to perform snesor-to-bone calibration
