### ISSUE TITLE
urdf文件的生成

### ISSUE THREAD

**Issue by mariolew** [Xinyu-Yi/PIP#7]
请问physics.urdf是依据什么生成的呢？自己想构造一个和mixamo骨架一致的需要怎么做呢？

**Comment by Xinyu-Yi** [comment]
我们从PhysCap的物理人体结构修改的

**Comment by Xinyu-Yi** [comment]
https://github.com/soshishimada/PhysCap_demo_release

**Comment by Xinyu-Yi** [comment]
如果需要其他骨架结构和质量分布，需要自己写

**Comment by jn-tang** [comment]
@Xinyu-Yi 你好，urdf文件中貌似把每个关节在xyz轴的上的旋转拆分成了3个revolute关节，请问我可以把3个revolute关节合并成ball-and-socket关节吗？我看到`left_hip_rz`, `left_hip_rx`和`left_hip_ry`对应的x, y, z坐标都不一样

**Comment by Xinyu-Yi** [comment]
> @Xinyu-Yi 你好，urdf文件中貌似把每个关节在xyz轴的上的旋转拆分成了3个revolute关节，请问我可以把3个revolute关节合并成ball-and-socket关节吗？我看到`left_hip_rz`, `left_hip_rx`和`left_hip_ry`对应的x, y, z坐标都不一样

应该是可以的，好像代码里会自动合成
