### ISSUE TITLE
real-time latency

### ISSUE THREAD

**Issue by yukichou** [Xinyu-Yi/PIP#9]
作者您好，我在实时推理时，将上一帧rnn的hidden state和cell state作为下一帧rnn的init时，发现帧率大大降低，平均帧率在30～40帧左右，动作有些卡顿。可以怎么做去缓解这种延迟呢？

**Comment by TowoC** [comment]
Hello, can you tell me how to solve this problem? I meet the same problem.
Thanks!

**Comment by NoLoPhe** [comment]
Hi @yukichou!

I also have problems with real-time inference.
